services:
  - type: web
    name: fastapi-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-postgres-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.9
    autoDeploy: true

databases:
  - name: my-postgres-db
    plan: free

