services:
  - type: web
    name: nexpath-backend
    runtime: python
    pythonVersion: "3.11.10"  # Keep quotes
    buildCommand: |
      pip install --upgrade pip
      pip install -r backend/requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker backend.main:app

    envVars:
      - key: MONGO_URI
        sync: false
      - key: POSTGRES_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: OTHER_API_URL
        sync: false

