services:
  - type: web
    name: nexpath-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: ./backend/start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nexpath-db
          property: connectionString
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        sync: false

databases:
  - name: nexpath-db
    plan: free
