services:
  - type: web
    name: nexpath-backend
    runtime: python
    pythonVersion: "3.11.10"  # Keep quotes
    buildCommand: |
      # Remove potentially conflicting files or old venvs
      rm -rf .venv
      mkdir -p backend/install

      # Create venv using the desired python version
      python3.11 -m venv .venv 

      # Use the pip executable *inside* the new venv
      ./.venv/bin/pip install --upgrade pip
      ./.venv/bin/pip install -r backend/requirements.txt
    startCommand: ./.venv/bin/gunicorn -k uvicorn.workers.UvicornWorker backend.main:app

    envVars:
      - key: MONGO_URI
        sync: false
      - key: POSTGRES_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: OTHER_API_URL
        sync: false

