services:
  - type: web
    name: nexpath-backend
    env: python
    pythonVersion: 3.11.10
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker backend.main:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: POSTGRES_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: OTHER_API_URL
        sync: false

