services:
  - type: web
    name: nexpath-backend
    runtime: python
    pythonVersion: "3.11.10"

    buildCommand: |
      # 1. Ensure Python 3.11 is what we think it is
      which python3.11
      python3.11 --version
      
      # 2. Use the python3.11 installation directly to install dependencies
      # We skip venv creation/activation to force the use of the 3.11 environment
      /usr/bin/python3.11 -m pip install --upgrade pip
      /usr/bin/python3.11 -m pip install -r backend/requirements.txt

    # 3. Use the gunicorn installed *via* python3.11 using 'python -m' syntax
    startCommand: python3.11 -m gunicorn -k uvicorn.workers.UvicornWorker backend.main:app


    envVars:
      - key: MONGO_URI
        sync: false
      - key: POSTGRES_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: OTHER_API_URL
        sync: false

