version: "3.1"

language: "en"  # Add this line to specify the language (English in this case)

# NLU pipeline for intent classification and entity extraction
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1

# Core policies for conversation flow
policies:
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100

assistant_id: 20250504-223209-frosty-triad
